name: fenestra_sdk_dart
description: Official sdk for fenestra_server.
version: 1.0.0
homepage: https://github.com/meg4cyberc4t/fenestra_sdk_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  
dependencies: 
  http: ^0.13.4
